### ISSUE TITLE
Two modules instead of one

### ISSUE THREAD

**Issue by R3D-CODE** [xulihang/barcode-detector-polyfill#3]
Could you please have two modules, one based on zxing, other dbr?
Supporting both just adds extra overhead and lake of focus

Also, zxing supports more formats than what you listed, any plan for supporting all formats?
What about
- multi-barcode detection
- ratio, resolution, blur, ...
- flash light
- ect?

**Comment by xulihang** [comment]
Please note that this library uses zxing-js. It does not support reading multiple barcodes and its supported formats are limited.
